### ISSUE TITLE
Fixup controls in Todo Applet

### ISSUE THREAD

**Issue by adaburrows** [neighbour-hoods/nh-launcher#169]
- [x] Remove extra border
- [x] Place icons in NHIconContainers
- [x] Add logic to freeze icons on select-start
- [x] Add logic to unfreeze icons on select-cancel
